source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZenLayout_Example', :exclusive => true do
  pod "ZenLayout", :path => "../"
end

target 'ZenLayout_Tests', :exclusive => true do
  pod "ZenLayout", :path => "../"

  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '~> 2.0.0-rc.3'
end
